### DISCUSSION TITLE
how to conditionally change textbox background color

### DISCUSSION THREAD

**Discussion by hafizmahmudi** [serenity-is/Serenity#5321] [Help]
Hi ;

I have an xxDialog.ts. There are two editor **first name** and **last name**. I would like to conditionally change the background color of these two controls on the dialog.

Is there a way to do it in serenity?

Thank you

**Comment by VictorTomaili** [comment]
@ms4hafiz I move this issue to discussion Q&A

**Reply by luongnv6** [reply]
xyzForm.cs
```C#
[CssClass("changeColor")]
public String FirstName {get; set;}
[CssClass("changeColor")]
public String LastName {get; set;}
```

in xyzIndex.cshtml
```css
<style>
    .changeColor .editor {
        background-color: red;
    }
</style>
```
