### DISCUSSION TITLE
EditorGrid resize

### DISCUSSION THREAD

**Discussion by kilroyFR** [serenity-is/Serenity#6593] [General]
Hey all, anyone did find the trick to autosize grid editor to fill the entire remaining bottom space of the form ?

![image](https://user-images.githubusercontent.com/31513956/203532886-c09c4f33-98e4-46fc-aa5c-3648eb95a5d4.png)

Thanks !

**Comment by volkanceylan** [comment]
Could be something like 
```css
@media (min-width: 996px) {
.s-MyDialog .s-MyEditor .slick-container {
    min-height: 100vh - 250px;
}
```

250px is the height of other items. I put a media rule so it only works in desktop etc. 

This is not tested.
