### DISCUSSION TITLE
Running Serenity/Serene/StartSharp on Docker in .NET 8

### DISCUSSION THREAD

**Discussion by edwardch** [serenity-is/Serenity#7030] [Tricks and Samples]
Hi Serenity community!

Firstly want to say thank you to the Serenity team for all the hard work on upgrading Serenity to .NET 6 and now .NET 8!

I had an app running on Docker in .NET 6, and have now managed to get my app running in Docker with .NET 8. 
(With the help from @VictorTomaili)

For those who want to run their app in Docker, here are some steps.

## Add Docker support

Right click on your project then `Add > Docker Support...`
This will create a `Dockerfile`. 

## Modify Dockerfile

To get it working (the way I needed, at least), I updated the contents of this file to the following:

```dockerfile
# I'm using some custom packages in the base image, which you can remove as you please
# fontconfig is installed because I want custom fonts for a third-party reporting tool
# Note that I use `fc-cache` (see comment at the end)
# lib* packages are related to exporting Excel and exporting custom reports mentioned above
# .NET 8 has change the default port to 8080
# See: https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port
# .Net 6 used 80, so if you are _upgrading_ to .NET 8, make sure to EXPOSE 8080

FROM mcr.microsoft.com/dotnet/aspnet:8.0-bookworm-slim AS base
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        fontconfig \
        libc6-dev \
        libgdiplus \
        libx11-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
EXPOSE 8080

# nodejs no longer uses https://deb.nodesource.com/setup_18.x method
# If anyone has a simpler method than below, please let me know
FROM mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim AS build
RUN apt-get update -yq \
    && apt-get upgrade -yq \
    && apt-get install -yq curl git nano ca-certificates gnupg \
    && mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
     | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && NODE_MAJOR=18 \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" \
     > /etc/apt/sources.list.d/nodesource.list \
    && apt-get update \
    && apt-get install nodejs -y
RUN npm install -g npm

# I use a custom NuGet.config file, hence my COPY and then --configfile usages
# Leave them out if you don't need them
WORKDIR /src
COPY ["NuGet.config", "."]
COPY ["MyApp/MyApp.Web/MyApp.Web.csproj", "MyApp/MyApp.Web/"]
RUN dotnet restore --configfile NuGet.config  "MyApp/MyApp.Web/MyApp.Web.csproj"
COPY . .
WORKDIR "/src/MyApp/MyApp.Web"
RUN dotnet build "MyApp.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MyApp.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MyApp.Web.dll"]
# If you want to mount custom fonts to /usr/share/fonts/truetype
# Replace above line with
# ENTRYPOINT fc-cache -f -v && dotnet MyApp.Web.dll
```

## Override appsettings (optional)

Then add a file next to `appsettings.json`, called **`appsettings.Docker.json`**
In this file you can override your settings, in my case it was to update connection strings accordingly to connect to a local or cloud based database.

## Run

Change your app to start Docker instead of IIS or Kestrel (whatever your choice), then hit run.

And that's it.

**Comment by heleopless50** [comment]
thanks so much for sharing 
can you explain what is the benefit of using docker over using kestrel or iis ?

**Reply by edwardch** [reply]
Could be for many reasons, as with software it always "depends", but here's an already made answer for you: https://stackify.com/10-reasons-to-use-docker-with-asp-net/

HTH!

**Comment by minhhungit** [comment]
Thanks for sharing @edwardch, btw this is what I used before, **hope it will give people more choices** 

**docker file**

```yaml
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y libpng-dev libjpeg-dev curl libxi6 build-essential libgl1-mesa-glx
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y nodejs

WORKDIR /src
COPY ["ContainerDemo/ContainerDemo.Web/ContainerDemo.Web.csproj", "ContainerDemo/ContainerDemo.Web/"]
COPY ["ContainerDemo/ContainerDemo.Web/nuget.config", "ContainerDemo/ContainerDemo.Web/"]
RUN dotnet restore "ContainerDemo/ContainerDemo.Web/ContainerDemo.Web.csproj"
COPY . .

WORKDIR "/src/ContainerDemo/ContainerDemo.Web"
RUN dotnet build "ContainerDemo.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ContainerDemo.Web.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ContainerDemo.Web.dll"]
```
---
**nuget.config file**

```xml
Nuget.config file

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <packageSources>
    <add key="public" value="https://api.nuget.org/v3/index.json" />
    <add key="customfeed" value="https://packages………/v3/index.json"  /> 
  </packageSources>

  <packageSourceCredentials>
    <customfeed>
      <add key="Username" value="enter_your_username" />
      <add key="ClearTextPassword" value="enter_your_raw_password" />
    </customfeed>
  </packageSourceCredentials>
</configuration>
```
---
**Database connection string**
```json
"Data": {
    "Default": {
      "ConnectionString": "Server=host.docker.internal\\MSSQLSERVER,1433;Database=ContainerDemo_Default_v1;User Id=jin;Password=adminp;Encrypt=false;TrustServerCertificate=true",
      "ProviderName": "System.Data.SqlClient"
    },
    "Northwind": {
      "ConnectionString": "Server=host.docker.internal\\MSSQLSERVER,1433;Database=ContainerDemo_Northwind_v1;User Id=jin;Password=adminp;Encrypt=false;TrustServerCertificate=true",
      "ProviderName": "System.Data.SqlClient"
    }
  },
```

**Reply by edwardch** [reply]
Nice, thanks @minhhungit 

Btw nodejs has seems to have moved on from install method. I used in in Azure before, and it no longer works, hence my key method.

And (from what I've read/understand) it's typically preferred to group install commands into a single `RUN` command, since each `RUN` creates a new layer.

Thanks for the additional nuget and config info!

**Reply by minhhungit** [reply]
yeah the file above is for old serenity .net 6 version

**Reply by edwardch** [reply]
@minhhungit  BTW it looks like nodesource have reverted the install method

https://github.com/nodesource/distributions#new-update-%EF%B8%8F

> - Installation Scripts: Back by popular demand, the installation scripts have returned and are better than ever. See the installation instructions below for details on how to use them.

https://github.com/nodesource/distributions/commit/55fa99e7bc3c5f1df38d245cf5c25ba3a304828b

**Comment by heleopless50** [comment]
can you provide the docker compose file to connect the docker file to mssql server in vps linux server ?

**Reply by edwardch** [reply]
Try something like this

```yaml
version: '3.4'

services:
  app:
    image: myapp/app
    build:
        context: .
        dockerfile: /MyApp/MyApp.Web/Dockerfile
    environment:
      - Data__Default__ConnectionString=Server=${DATABASE_SERVER};Database=${DATABASE_NAME};User Id=sa;Password=${DATABASE_PASSWORD};
      - Data__MyApp__ConnectionString=Server=${DATABASE_SERVER};Database=${DATABASE_NAME};User Id=sa;Password=${DATABASE_PASSWORD};
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./MyApp/MyApp.Web/App_Data:/app/App_Data
      - ./MyApp/MyApp.Web/App_Data/upload/fonts:/usr/share/fonts/truetype
    depends_on:
      - sqldata
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=${DATABASE_PASSWORD}
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "5434:1433"
    volumes:
      - ./.data:/var/opt/mssql/data
    restart: "on-failure"
```
